data:
  input_paths:
    - dataset/Data_10k_sets/Data_10k_rng1/LHS_parameters_m.txt
    - dataset/Data_10k_sets/Data_10k_rng2/LHS_parameters_m.txt
    - dataset/Data_10k_sets/Data_10k_rng3/LHS_parameters_m.txt
  output_paths:
    - dataset/Data_10k_sets/Data_10k_rng1/iV_m.txt
    - dataset/Data_10k_sets/Data_10k_rng2/iV_m.txt
    - dataset/Data_10k_sets/Data_10k_rng3/iV_m.txt
  test_size: 0.2
  batch_size: 32
  num_workers: 4
  pin_memory: true

training:
  epochs: 20
  learning_rate: 1.0e-3
  max_grad_norm: 1.0
  save_dir: ./checkpoints/sequence
  save_interval: 5
  log_interval: 10
  early_stopping_patience: 5

model:
  type: sequence
  physical_dim: 31
  hidden_dim: 64
  num_layers: 1
  dropout: 0.2
  teacher_forcing_ratio: 0.5